import { $api } from '@/common/axios/instance';
import { MenuItem } from '@/common/models/menu/menu';
import { Htag } from '@/components';
import { Button, ButtonTheme } from '@/components/Button/Button.tsx';
import { P, PSize } from '@/components/P/P.tsx';
import { Rating } from '@/components/Rating/Rating.tsx';
import { Tag, TagColor, TagSize } from '@/components/Tag/Tag.tsx';
import { getLayout } from '@/layout/Layout.tsx';
import { NextPageWithLayout } from '@/pages/_app.tsx';
import { AxiosResponse } from 'axios';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { useState } from 'react';

const Home: NextPageWithLayout<HomeProps> = (props): JSX.Element => {
  const { menu } = props;
  const [rat, setRat] = useState(0);
  console.log(rat);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <ul>
          {menu.map((m) => (
            <li key={m._id.secondCategory}>{m._id.secondCategory}</li>
          ))}
        </ul>
        <Htag tag='h1'>123</Htag>
        <Button>LOL</Button>
        <Button theme={ButtonTheme.GHOST} arrow={'right'}>
          LOL
        </Button>
        <P size={PSize.S}>Маленький</P>
        <P>Средний</P>
        <P size={PSize.L}>Большой</P>
        <Tag size={TagSize.M} color={TagColor.GHOST}>
          Тег
        </Tag>
        <Tag size={TagSize.M} color={TagColor.RED}>
          Тег
        </Tag>
        <Tag size={TagSize.M} color={TagColor.GRAY}>
          Тег
        </Tag>
        <Tag href={'#'} size={TagSize.M} color={TagColor.GREEN}>
          Тег
        </Tag>
        <Tag size={TagSize.M}>Тег</Tag>
        <Rating rating={rat} isEditable setRating={setRat} />
      </main>
    </>
  );
};
Home.getLayout = getLayout;
export default Home;

export const getStaticProps: GetStaticProps<HomeProps> = async (ctx) => {
  const firstCategory: number = 0;
  const { data: menu } = await $api.post<'', AxiosResponse<MenuItem[]>, { firstCategory: number }>(
    'api/top-page/find',
    { firstCategory }
  );
  return {
    props: {
      menu,
      firstCategory
    }
  };
};

interface HomeProps {
  menu: MenuItem[];
  firstCategory: number;
}
